### ISSUE TITLE
package update than show issue flutter_quill: ^3.0.0

### ISSUE THREAD

**Issue by arupnaskarbkp** [friebetill/delta_markdown#4]
Because delta_markdown 0.3.0 depends on flutter_quill ^2.0.0 and no versions of delta_markdown match >0.3.0 <0.4.0, delta_markdown ^0.3.0 requires flutter_quill ^2.0.0.
So, because lms_teacher depends on both delta_markdown ^0.3.0 and flutter_quill ^3.0.0, version solving failed.
pub get failed (1; So, because lms_teacher depends on both delta_markdown ^0.3.0 and flutter_quill ^3.0.0, version solving failed.)
Process finished with exit code 1

**Comment by matthiasn** [comment]
Same issue here, would be nice to have this fixed and be able to upgrade `flutter_quill`.

**Comment by matthiasn** [comment]
@arupnaskarbkp I created PR #5 for this. Until that is merged, you can use my fork, see [this commit](https://github.com/matthiasn/meins/pull/653/commits/73a10bd13baf3c7e74a5239be5b45ddd689846a7).

**Comment by friebetill** [comment]
I released [version 0.4.0](https://pub.dev/packages/delta_markdown) with the update from @matthiasn.

**Comment by matthiasn** [comment]
Thanks @friebetill
