### ISSUE TITLE
Does not support flutter_quill >3.4.4

### ISSUE THREAD

**Issue by raveesh-me** [friebetill/delta_markdown#6]
Looks like flutter_quill had a breaking change in the way they export stuff (models etc are no longer exposed)
So to use delta_markdown we are having to cap flutter_quill to 3.4.4 for now

**Comment by devtud** [comment]
https://github.com/friebetill/delta_markdown/pull/7

**Comment by friebetill** [comment]
I have published two versions:
- 0.5.0: The version is compatible with `flutter_quill` 3.8.7 - <4.0.0 
- 0.6.0: The version is compatible with `flutter_quill` >= 4.0.0
